
CREATE TABLE IF NOT EXISTS GRAPH(
    id VARCHAR(255) PRIMARY KEY,
    created TIMESTAMP);

CREATE TABLE IF NOT EXISTS GRAPH_ENTRY(
    graph_id VARCHAR(255) FOREIGN KEY  REFERENCES  GRAPH(id) ,
    element VARCHAR(255) NOT NULL);